---
title: "11.- Visualización_nivel_actividad_fisica"
author: "Abel_Sánchez"
date: "`r Sys.Date()`"
output: html_document
---

```{r cargar-librerias, warning=TRUE, paged.print=TRUE}
# Configurar el directorio de trabajo
if (.Platform$OS.type == "windows") {
  setwd("C:/Users/FX506/Documents/Portafolio/Bellabeat_2016")
} else {
  setwd("~/Portafolio/Bellabeat_2016")
}

# Limpiar el entorno
rm(list = ls())
gc()

#Cargar librerias
library(readxl)
library(tidyverse)
library(janitor)

# Definir la ruta del archivo Excel
file_path <- "data/minsa/raw/datos_ense2017_resumen.xls"

# Leer el archivo Excel y seleccionar el rango de datos
actividad_fisica <- read_excel(file_path, sheet = "T3066_nivel_actividad_fisica", range = "A1:D9", col_types = "text")

# Limpiar nombres de columnas
actividad_fisica_clean <- actividad_fisica %>%
  janitor::clean_names()

# Convertir las columnas seleccionadas a numéricas y reemplazar comas por puntos
actividad_fisica_clean <- actividad_fisica_clean %>%
  mutate(across(nivel_alto:nivel_bajo, ~ as.numeric(str_replace_all(., ",", "."))))

# Inspeccionar la estructura de los datos limpiados
str(actividad_fisica_clean)
head(actividad_fisica_clean)
summary(actividad_fisica_clean)

# Reorganizar los datos en un formato adecuado para graficar
actividad_fisica_melted <- actividad_fisica_clean %>%
  pivot_longer(cols = nivel_alto:nivel_bajo, names_to = "nivel_actividad", values_to = "porcentaje")

# Normalizar los datos dentro de cada grupo etareo
actividad_fisica_melted <- actividad_fisica_melted %>%
  group_by(mujeres) %>%
  mutate(porcentaje = porcentaje / sum(porcentaje, na.rm = TRUE) * 100) %>%
  ungroup()

summary(cars)
```

## Including Plots

```{r pressure, echo=FALSE}
# Crear el gráfico de barras
actividad_fisica_melted %>%
  ggplot(aes(x = mujeres, y = porcentaje, fill = nivel_actividad)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Nivel de Actividad Física por Grupo Etareo",
       x = "Grupo Etareo",
       y = "Porcentaje",
       fill = "Nivel de Actividad") +
  theme_minimal()
```